version: '3.8'

services:
  model-api:
    build:
      context: .
      dockerfile: Dockerfile  # Путь к вашему Dockerfile
    ports:
      - "5000:5000"  # Порт для доступа к API
    environment:
      - PYTHONUNBUFFERED=1  # Переменная окружения для правильного вывода логов
    volumes:
      - .:/app  # Монтирование локальной папки в контейнер
    restart: always  # Автоперезапуск в случае падения контейнера
    # command: python app.py  # Replace this with the actual script you want to run
