version: '3.8'

services:
  transformers-app:
    build: .
    container_name: transformers_container
    volumes:
      - ./:/app  # Mounts the current directory to /app in the container
    ports:
      - "8080:8080"  # Map port 8080 of the container to port 8080 on the host (adjust as needed)
    environment:
      - PYTHONUNBUFFERED=1  # Ensures that Python output is logged in real-time
    command: python app.py  # Replace this with the actual script you want to run
